name = "Qwen3 VL 235B"
release_date = "2026-01-16"
last_updated = "2026-06-11"
attachment = true
reasoning = false
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.25
output = 1.5

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
